version: '3.8'

services:
  geo:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
      - rabbit
  notification:
    build:
      context: ../notifcation
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
      - rabbit
      - geo
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 4s
      timeout: 20s
      retries: 10
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=geoservicedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cache:
    image: redis:latest
