version: '3.8'

services:
  geo1:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
      - cache
  geo2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - db
      - cache
  geo3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - db
      - cache
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=geoservicedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    image: redis:latest

volumes:
  postgres_data:
